stages:
  - build
  - test
  - deploy

build:
  stage: test
  image: dindonino/ybook-back:latest
  cache:
    paths:
      - node_modules/
  variables:
    CI: "false"
  script:
    - echo "Start building"
    - npm install
    - npm run build
    - echo "Build successfully"
  tags:
    - run-on-docker

test:
  stage: test
  image: dindonino/ybook-back:latest
  script:
    - echo "testing..."
    - npm install
    - npm run typecheck
    - echo "Type is corrects"

  tags:
    - run-on-docker

deploy:
  stage: deploy
  image: alpine
  tags:
    - run-on-docker
  variables: 
    GIT_STRATEGY: none
  script:
    - echo "deployment..."
    - npm run start