stages:
  - build
  - test
  - deploy

build:
  stage: test
  image: dindonino/ybook-back:latest
  cache:
    paths:
      - node_modules/
  variables:
    CI: "false"
  script:
    - echo "Start building"
    - npm ci
    - npm run build
    - echo "Build successfully"
  tags:
    - run-on-docker

build:
  stage: test

deploy:
  stage: deploy
  variables: 
    GIT_STRATEGY: none