version: "3"
services:
  prisma-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-api
    env_file:
      - .env
    ports:
      - "3100:3100"
    restart: always
