version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=azertyuiop
      - POSTGRES_DB=prismamobile
    volumes:
      - ./appdata/postgres:/var/lib/postgresql/data
    networks:
      - postgresdb
    ports:
      - "5432:5432"

networks:
  postgresdb:
    external: false